import { grass, indigo, orange, sand, tomato, yellow } from "@radix-ui/colors";

export const colors = {
  primary: {
    1: orange.orange1,
    2: orange.orange2,
    3: orange.orange3,
    4: orange.orange4,
    5: orange.orange5,
    6: orange.orange6,
    7: orange.orange7,
    8: orange.orange8,
    9: orange.orange9,
    10: orange.orange10,
    11: orange.orange11,
    12: orange.orange11,
  },

  neutral: {
    1: sand.sand1,
    2: sand.sand2,
    3: sand.sand3,
    4: sand.sand4,
    5: sand.sand5,
    6: sand.sand6,
    7: sand.sand7,
    8: sand.sand8,
    9: sand.sand9,
    10: sand.sand10,
    11: sand.sand11,
    12: sand.sand11,
  },

  secondary: {
    1: indigo.indigo1,
    2: indigo.indigo2,
    3: indigo.indigo3,
    4: indigo.indigo4,
    5: indigo.indigo5,
    6: indigo.indigo6,
    7: indigo.indigo7,
    8: indigo.indigo8,
    9: indigo.indigo9,
    10: indigo.indigo10,
    11: indigo.indigo11,
    12: indigo.indigo11,
  },

  success: {
    1: grass.grass1,
    2: grass.grass2,
    3: grass.grass3,
    4: grass.grass4,
    5: grass.grass5,
    6: grass.grass6,
    7: grass.grass7,
    8: grass.grass8,
    9: grass.grass9,
    10: grass.grass10,
    11: grass.grass11,
    12: grass.grass11,
  },

  danger: {
    1: tomato.tomato1,
    2: tomato.tomato2,
    3: tomato.tomato3,
    4: tomato.tomato4,
    5: tomato.tomato5,
    6: tomato.tomato6,
    7: tomato.tomato7,
    8: tomato.tomato8,
    9: tomato.tomato9,
    10: tomato.tomato10,
    11: tomato.tomato11,
    12: tomato.tomato11,
  },

  warning: {
    1: yellow.yellow1,
    2: yellow.yellow2,
    3: yellow.yellow3,
    4: yellow.yellow4,
    5: yellow.yellow5,
    6: yellow.yellow6,
    7: yellow.yellow7,
    8: yellow.yellow8,
    9: yellow.yellow9,
    10: yellow.yellow10,
    11: yellow.yellow11,
    12: yellow.yellow11,
  },
};
